package com.business.book.entity.constants;

public enum Status {
    ENTREPRISE_INDIVIDUELLE,
    SOCIETE_A_RESPONSABILITE_LIMITEE,
    SOCIETE_ANONYME,
    SOCIETE_EN_NOM_COLLECTIF,
    SOCIETE_EN_COMMANDITE_SIMPLE,
    SOCIETE_COOPERATIVE,
    GROUPEMENT_D_INTERET_ECONOMIQUE,
    SOCIETE_CIVILE,
    SUCCURSALE,
    SOCIETE_UNIPERSONNELLE_A_RESPONSABILITE_LIMITEE,
    ACTIVE
}
